apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: checkout
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: accountName
    value: "advtechstorage"
  - name: accountKey
    secretKeyRef:
      name: blob-masterKey
      key:  blob-masterKey
  - name: queueName
    value: "orders"
auth:
  secretStore: azurekeyvault