apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgresqlapp
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: postgresql-connectionString
      key:  postgresql-connectionString
auth:
  secretStore: azurekeyvault
