apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: uploadblobapp
  namespace: default
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: "advtechcontainerblob"
  - name: storageAccessKey
    secretKeyRef:
      name: blob-masterKey
      key:  blob-masterKey
  - name: container
    value: "advtechcontainerblob"
  - name: decodeBase64
    value: true
auth:
  secretStore: azurekeyvault
