# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /api
EXPOSE 80

# copy csproj and restore as distinct layers
WORKDIR /api/delivery
COPY ./delivery/delivery.csproj ./
RUN dotnet restore

# copy everything else and build app
WORKDIR /api
COPY ./delivery/ ./delivery/

WORKDIR /api/delivery
RUN dotnet publish -c release -o delivery -r ubuntu.18.04-x64

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=build / ./
WORKDIR /api/delivery
ENTRYPOINT ["dotnet", "bin/release/net6.0/ubuntu.18.04-x64/delivery.dll"]
