name: Trigger auto deployment for operationsapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/operationsapp-AutoDeployTrigger-8e65b119-30a0-4767-b8f9-2810aa5406df.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: advtechregistry.azurecr.io
          username: ${{ secrets.OPERATIONSAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.OPERATIONSAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: advtechregistry.azurecr.io/operationsapp:${{ github.sha }}
          file: ./api/operations/dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OPERATIONSAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n operationsapp -g adv-tech-days --server advtechregistry.azurecr.io --username  ${{ secrets.OPERATIONSAPP_REGISTRY_USERNAME }} --password ${{ secrets.OPERATIONSAPP_REGISTRY_PASSWORD }}
            az containerapp update -n operationsapp -g adv-tech-days --image advtechregistry.azurecr.io/operationsapp:${{ github.sha }}
